#!/usr/bin/env python3
"""Create report-ready figures from summaries generated by analyze.py."""

from __future__ import annotations

from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import pandas as pd


ROOT = Path(__file__).resolve().parents[1]
PLATFORM_KEYS = ("macos-arm64", "windows-x86_64")
PLATFORM_LABELS = {"macos-arm64": "Apple M5（macOS/ARM64）", "windows-x86_64": "Intel Core i5-12400F（Windows/x86-64）"}
VARIANT_LABELS = {
    "sequential": "顺序访问",
    "random": "随机访问",
    "serial": "单线程",
    "parallel": "多线程",
    "eratosthenes": "埃拉托斯特尼筛法",
    "hoare": "Hoare 快速排序",
}

# PingFang SC ships with macOS. The later fallbacks also cover common Windows
# and Linux environments, preserving Chinese labels across both test hosts.
plt.rcParams["font.sans-serif"] = ["PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", "SimHei", "DejaVu Sans"]
plt.rcParams["axes.unicode_minus"] = False


def load_summaries() -> dict[str, pd.DataFrame]:
    summaries: dict[str, pd.DataFrame] = {}
    for key in PLATFORM_KEYS:
        path = ROOT / "results" / key / "summary" / "summary.csv"
        summaries[key] = pd.read_csv(path) if path.exists() else pd.DataFrame()
    return summaries


def save_or_skip(figure: plt.Figure, path: Path, has_data: bool) -> None:
    if has_data:
        figure.tight_layout()
        figure.savefig(path, dpi=160)
        print(f"Wrote {path}")
    else:
        print(f"Skipped {path.name}: matching data is not available yet.")
    plt.close(figure)


def matrix_time(summaries: dict[str, pd.DataFrame], output: Path) -> None:
    figure, axis = plt.subplots(figsize=(7, 4.5))
    has_data = False
    for key, summary in summaries.items():
        if summary.empty:
            continue
        rows = summary[(summary["benchmark"] == "matrix") & (summary["variant"] == "serial")].sort_values("size")
        if rows.empty:
            continue
        axis.errorbar(rows["size"], rows["time_mean_ms"], yerr=rows["time_std_ms"].fillna(0), marker="o", capsize=3,
                      label=PLATFORM_LABELS[key])
        has_data = True
    axis.set(xlabel="矩阵维度 N", ylabel="平均执行时间（ms）", title="矩阵乘法执行时间")
    axis.grid(True, alpha=0.3)
    if has_data:
        axis.legend()
    save_or_skip(figure, output / "matrix_execution_time.png", has_data)


def matrix_gflops(summaries: dict[str, pd.DataFrame], output: Path) -> None:
    figure, axis = plt.subplots(figsize=(7, 4.5))
    has_data = False
    for key, summary in summaries.items():
        if summary.empty:
            continue
        rows = summary[(summary["benchmark"] == "matrix") & (summary["variant"] == "serial")].sort_values("size")
        if rows.empty:
            continue
        axis.errorbar(rows["size"], rows["metric_mean"], yerr=rows["metric_std"].fillna(0), marker="o", capsize=3,
                      label=PLATFORM_LABELS[key])
        has_data = True
    axis.set(xlabel="矩阵维度 N", ylabel="GFLOPS", title="矩阵乘法浮点性能")
    axis.grid(True, alpha=0.3)
    if has_data:
        axis.legend()
    save_or_skip(figure, output / "matrix_gflops.png", has_data)


def problem_size_comparison(
    summaries: dict[str, pd.DataFrame],
    output: Path,
    benchmark: str,
    xlabel: str,
    title: str,
    filename: str,
) -> None:
    """Plot mean ± standard deviation for one scalar problem-size sweep."""
    figure, axis = plt.subplots(figsize=(7, 4.5))
    has_data = False
    for key, summary in summaries.items():
        if summary.empty:
            continue
        rows = summary[summary["benchmark"] == benchmark].sort_values("size")
        if rows.empty:
            continue
        axis.errorbar(
            rows["size"],
            rows["time_mean_ms"],
            yerr=rows["time_std_ms"].fillna(0),
            marker="o",
            capsize=3,
            label=PLATFORM_LABELS[key],
        )
        has_data = True
    axis.set_xscale("log")
    axis.set(xlabel=xlabel, ylabel="平均执行时间（ms）", title=title)
    axis.grid(True, which="both", alpha=0.3)
    if has_data:
        axis.legend()
    save_or_skip(figure, output / filename, has_data)


def scaling(summaries: dict[str, pd.DataFrame], output: Path, column: str, ylabel: str, filename: str) -> None:
    figure, axis = plt.subplots(figsize=(7, 4.5))
    has_data = False
    largest_thread = 1
    for key, summary in summaries.items():
        if summary.empty or column not in summary:
            continue
        rows = summary[(summary["benchmark"] == "matrix") & summary[column].notna()].copy()
        if rows.empty:
            continue
        # Default runs have a sweep at N=512 plus larger serial-only sizes.
        # Prefer the largest size that actually has multiple thread samples;
        # otherwise fall back to the largest available size.
        thread_counts = rows.groupby("size")["threads"].nunique()
        sweep_sizes = thread_counts[thread_counts > 1]
        selected_size = sweep_sizes.index.max() if not sweep_sizes.empty else rows["size"].max()
        rows = rows[rows["size"] == selected_size].sort_values("threads")
        axis.plot(rows["threads"], rows[column].astype(float), marker="o", label=PLATFORM_LABELS[key])
        largest_thread = max(largest_thread, int(rows["threads"].max()))
        has_data = True
    if column == "speedup":
        axis.plot([1, largest_thread], [1, largest_thread], "k--", label="理想加速比")
    title = "矩阵乘法多核加速比" if column == "speedup" else "矩阵乘法并行效率"
    axis.set(xlabel="线程数", ylabel=ylabel, title=title)
    axis.grid(True, alpha=0.3)
    if has_data:
        axis.legend()
    save_or_skip(figure, output / filename, has_data)


def memory_performance(summaries: dict[str, pd.DataFrame], output: Path) -> None:
    figure, axis = plt.subplots(figsize=(7, 4.5))
    has_data = False
    for key, summary in summaries.items():
        if summary.empty:
            continue
        for variant, style in (("sequential", "-"), ("random", "--")):
            rows = summary[(summary["benchmark"] == "memory") & (summary["variant"] == variant)].sort_values("size")
            if rows.empty:
                continue
            axis.plot(rows["size"], rows["metric_mean"], style, marker="o",
                      label=f"{PLATFORM_LABELS[key]} — {VARIANT_LABELS[variant]}")
            has_data = True
    axis.set_xscale("log", base=2)
    axis.set(xlabel="工作集大小（字节，对数坐标）", ylabel="百万次访问 / 秒", title="内存访问性能")
    axis.grid(True, which="both", alpha=0.3)
    if has_data:
        axis.legend(fontsize=8)
    save_or_skip(figure, output / "memory_performance.png", has_data)


def remove_obsolete_outputs(output: Path) -> None:
    """Keep the figure directory aligned with the report-oriented filenames."""
    for filename in (
        "relative_performance.png",
        "matrix_multicore_speedup.png",
        "matrix_parallel_efficiency.png",
        "overall_speedup.png",
    ):
        path = output / filename
        if path.exists():
            path.unlink()
            print(f"Removed obsolete {path}")


def main() -> None:
    output = ROOT / "results" / "comparison" / "figures"
    output.mkdir(parents=True, exist_ok=True)
    summaries = load_summaries()
    remove_obsolete_outputs(output)
    problem_size_comparison(summaries, output, "sieve", "筛选上限（对数坐标）", "筛法执行时间", "sieve_comparison.png")
    problem_size_comparison(summaries, output, "quicksort", "元素数量（对数坐标）", "快速排序执行时间", "quicksort_comparison.png")
    matrix_time(summaries, output)
    matrix_gflops(summaries, output)
    scaling(summaries, output, "speedup", "加速比", "multicore_speedup.png")
    scaling(summaries, output, "parallel_efficiency", "并行效率", "parallel_efficiency.png")
    memory_performance(summaries, output)


if __name__ == "__main__":
    main()
