#!/usr/bin/env python3
"""Create report-ready figures from summaries generated by analyze.py."""

from __future__ import annotations

from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import pandas as pd


ROOT = Path(__file__).resolve().parents[1]
PLATFORM_KEYS = ("macos-arm64", "windows-x86_64")
PLATFORM_LABELS = {"macos-arm64": "Apple M5 (macOS/ARM64)", "windows-x86_64": "Intel Core i5-12400F (Windows/x86-64)"}


def load_summaries() -> dict[str, pd.DataFrame]:
    summaries: dict[str, pd.DataFrame] = {}
    for key in PLATFORM_KEYS:
        path = ROOT / "results" / key / "summary" / "summary.csv"
        summaries[key] = pd.read_csv(path) if path.exists() else pd.DataFrame()
    return summaries


def save_or_skip(figure: plt.Figure, path: Path, has_data: bool) -> None:
    if has_data:
        figure.tight_layout()
        figure.savefig(path, dpi=160)
        print(f"Wrote {path}")
    else:
        print(f"Skipped {path.name}: matching data is not available yet.")
    plt.close(figure)


def matrix_time(summaries: dict[str, pd.DataFrame], output: Path) -> None:
    figure, axis = plt.subplots(figsize=(7, 4.5))
    has_data = False
    for key, summary in summaries.items():
        if summary.empty:
            continue
        rows = summary[(summary["benchmark"] == "matrix") & (summary["variant"] == "serial")].sort_values("size")
        if rows.empty:
            continue
        axis.errorbar(rows["size"], rows["time_mean_ms"], yerr=rows["time_std_ms"].fillna(0), marker="o", capsize=3,
                      label=PLATFORM_LABELS[key])
        has_data = True
    axis.set(xlabel="Matrix dimension N", ylabel="Mean execution time (ms)", title="Matrix multiplication execution time")
    axis.grid(True, alpha=0.3)
    if has_data:
        axis.legend()
    save_or_skip(figure, output / "matrix_execution_time.png", has_data)


def matrix_gflops(summaries: dict[str, pd.DataFrame], output: Path) -> None:
    figure, axis = plt.subplots(figsize=(7, 4.5))
    has_data = False
    for key, summary in summaries.items():
        if summary.empty:
            continue
        rows = summary[(summary["benchmark"] == "matrix") & (summary["variant"] == "serial")].sort_values("size")
        if rows.empty:
            continue
        axis.errorbar(rows["size"], rows["metric_mean"], yerr=rows["metric_std"].fillna(0), marker="o", capsize=3,
                      label=PLATFORM_LABELS[key])
        has_data = True
    axis.set(xlabel="Matrix dimension N", ylabel="GFLOPS", title="Matrix multiplication throughput")
    axis.grid(True, alpha=0.3)
    if has_data:
        axis.legend()
    save_or_skip(figure, output / "matrix_gflops.png", has_data)


def scaling(summaries: dict[str, pd.DataFrame], output: Path, column: str, ylabel: str, filename: str) -> None:
    figure, axis = plt.subplots(figsize=(7, 4.5))
    has_data = False
    largest_thread = 1
    for key, summary in summaries.items():
        if summary.empty or column not in summary:
            continue
        rows = summary[(summary["benchmark"] == "matrix") & summary[column].notna()].copy()
        if rows.empty:
            continue
        # Default runs have a sweep at N=512 plus larger serial-only sizes.
        # Prefer the largest size that actually has multiple thread samples;
        # otherwise fall back to the largest available size.
        thread_counts = rows.groupby("size")["threads"].nunique()
        sweep_sizes = thread_counts[thread_counts > 1]
        selected_size = sweep_sizes.index.max() if not sweep_sizes.empty else rows["size"].max()
        rows = rows[rows["size"] == selected_size].sort_values("threads")
        axis.plot(rows["threads"], rows[column].astype(float), marker="o", label=PLATFORM_LABELS[key])
        largest_thread = max(largest_thread, int(rows["threads"].max()))
        has_data = True
    if column == "speedup":
        axis.plot([1, largest_thread], [1, largest_thread], "k--", label="Ideal speedup")
    axis.set(xlabel="Thread count", ylabel=ylabel, title=ylabel + " for matrix multiplication")
    axis.grid(True, alpha=0.3)
    if has_data:
        axis.legend()
    save_or_skip(figure, output / filename, has_data)


def memory_performance(summaries: dict[str, pd.DataFrame], output: Path) -> None:
    figure, axis = plt.subplots(figsize=(7, 4.5))
    has_data = False
    for key, summary in summaries.items():
        if summary.empty:
            continue
        for variant, style in (("sequential", "-"), ("random", "--")):
            rows = summary[(summary["benchmark"] == "memory") & (summary["variant"] == variant)].sort_values("size")
            if rows.empty:
                continue
            axis.plot(rows["size"], rows["metric_mean"], style, marker="o", label=f"{PLATFORM_LABELS[key]} — {variant}")
            has_data = True
    axis.set_xscale("log", base=2)
    axis.set(xlabel="Working set (bytes, log scale)", ylabel="Million accesses / second", title="Memory access performance")
    axis.grid(True, which="both", alpha=0.3)
    if has_data:
        axis.legend(fontsize=8)
    save_or_skip(figure, output / "memory_performance.png", has_data)


def overall_comparison(output: Path) -> None:
    figure, axis = plt.subplots(figsize=(9, 5))
    path = ROOT / "results" / "comparison" / "summary" / "comparison.csv"
    comparison = pd.read_csv(path) if path.exists() else pd.DataFrame()
    if comparison.empty or "speedup_m5" not in comparison:
        save_or_skip(figure, output / "relative_performance.png", False)
        return
    rows = comparison.copy()
    rows["label"] = rows.apply(lambda row: f"{row['benchmark']}:{row['variant']}\n{int(row['size'])}, t={int(row['threads'])}", axis=1)
    axis.bar(range(len(rows)), rows["speedup_m5"], color="#4C78A8")
    axis.axhline(1.0, color="black", linewidth=1)
    axis.set_xticks(range(len(rows)), rows["label"], rotation=60, ha="right")
    axis.set(ylabel="Speedup of M5 = T(i5-12400F) / T(M5)", title="Relative performance by workload")
    axis.grid(True, axis="y", alpha=0.3)
    save_or_skip(figure, output / "relative_performance.png", True)


def main() -> None:
    output = ROOT / "results" / "comparison" / "figures"
    output.mkdir(parents=True, exist_ok=True)
    summaries = load_summaries()
    matrix_time(summaries, output)
    matrix_gflops(summaries, output)
    scaling(summaries, output, "speedup", "Speedup", "matrix_multicore_speedup.png")
    scaling(summaries, output, "parallel_efficiency", "Parallel efficiency", "matrix_parallel_efficiency.png")
    memory_performance(summaries, output)
    overall_comparison(output)


if __name__ == "__main__":
    main()
